### ISSUE TITLE
Nice library :)

### ISSUE THREAD

**Issue by jamesfoster** [asgerhallas/ShouldBeLike#2]
Hey hey. No issue. Just to say I like what you've done here.

I've released an update today. Version 4 fixes some of the things you're  doing here. Such as `Inconclusive` results are treated as a failure now. And comparing two empty objects returns a `Pass` result. 

Keep up the good work

**Comment by asgerhallas** [comment]
@jamesfoster Thanks! And thanks for making DeepEqual. 

I would have integrated your latest update right away, but the upgrade away from netstandard2.0 makes that hard, as I still use it in dotnet core projects :')

Any chance of at least supporting netstandard2.1?

**Comment by asgerhallas** [comment]
@jamesfoster ah nice! I didn't see the 4.1.0 update. Thanks a lot.
